--
-- PostgreSQL database dump
--

\restrict lJB4AVx7hnqavRzrZiaJUUNfDzFPkwlogdOJsmAuUYtyrmUfbrEVf2IFn6ccqcC

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bodega; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bodega (
    id integer NOT NULL,
    codigo character varying(5) NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(255) NOT NULL,
    dotacion integer NOT NULL,
    estado character varying(20) DEFAULT 'Activada'::character varying NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT bodega_codigo_check CHECK (((codigo)::text ~ '^B[A-Za-z0-9]{1,4}$'::text)),
    CONSTRAINT bodega_estado_check CHECK (((estado)::text = ANY ((ARRAY['Activada'::character varying, 'Desactivada'::character varying])::text[])))
);


ALTER TABLE public.bodega OWNER TO postgres;

--
-- Name: bodega_encargado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bodega_encargado (
    id integer NOT NULL,
    bodega_id integer NOT NULL,
    encargado_id integer NOT NULL,
    fecha_asignacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado character varying(20) DEFAULT 'Activo'::character varying NOT NULL,
    CONSTRAINT bodega_encargado_estado_check CHECK (((estado)::text = ANY ((ARRAY['Activo'::character varying, 'Inactivo'::character varying])::text[])))
);


ALTER TABLE public.bodega_encargado OWNER TO postgres;

--
-- Name: bodega_encargado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bodega_encargado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bodega_encargado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bodega_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bodega ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bodega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: encargado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.encargado (
    id integer NOT NULL,
    run character varying(20) NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido1 character varying(50) NOT NULL,
    apellido2 character varying(50),
    direccion character varying(255),
    telefono character varying(20)
);


ALTER TABLE public.encargado OWNER TO postgres;

--
-- Name: encargado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.encargado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.encargado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bodega bodega_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bodega
    ADD CONSTRAINT bodega_codigo_key UNIQUE (codigo);


--
-- Name: bodega_encargado bodega_encargado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bodega_encargado
    ADD CONSTRAINT bodega_encargado_pkey PRIMARY KEY (id);


--
-- Name: bodega bodega_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bodega
    ADD CONSTRAINT bodega_pkey PRIMARY KEY (id);


--
-- Name: encargado encargado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.encargado
    ADD CONSTRAINT encargado_pkey PRIMARY KEY (id);


--
-- Name: encargado encargado_run_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.encargado
    ADD CONSTRAINT encargado_run_key UNIQUE (run);


--
-- Name: bodega_encargado unique_bodega_encargado; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bodega_encargado
    ADD CONSTRAINT unique_bodega_encargado UNIQUE (bodega_id, encargado_id);


--
-- Name: bodega_encargado fk_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bodega_encargado
    ADD CONSTRAINT fk_bodega FOREIGN KEY (bodega_id) REFERENCES public.bodega(id);


--
-- Name: bodega_encargado fk_encargado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bodega_encargado
    ADD CONSTRAINT fk_encargado FOREIGN KEY (encargado_id) REFERENCES public.encargado(id);


INSERT INTO encargado (run, nombre, apellido1, apellido2, direccion, telefono)
VALUES
  ('28-9', 'Sebastian', 'Velazques', 'Contreras', 'Av. Siempre Viva 123','923456788'),
  ('98765432-1', 'Elisabeth', 'Beaufort', 'Swan', 'Calle Falsa 456', '987654321');

INSERT INTO bodega (codigo, nombre, direccion, dotacion, estado)
VALUES
  ('B0012', 'Bodega Central', 'Santiago Centro', 10, 'Activada');

--
-- PostgreSQL database dump complete
--

\unrestrict lJB4AVx7hnqavRzrZiaJUUNfDzFPkwlogdOJsmAuUYtyrmUfbrEVf2IFn6ccqcC

